# Dockerfile
FROM node:12 AS base
WORKDIR /app
COPY ./package*.json ./
# COPY ./env_file ./
COPY ./dist ./dist
RUN npm ci --only=production

FROM node:12-alpine
WORKDIR /app
COPY --from=base /app .
# COPY . .

EXPOSE 3000

CMD ["node",  "dist/main.js"]
