apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-botmanager.fullname" . }}
  labels:
    {{- include "helm-botmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.port}}
      nodePort: {{.Values.service.nodePort}}
  selector:
    {{- include "helm-botmanager.selectorLabels" . | nindent 4 }}
